title: Karbonara, Inc.
email: hello@trycarbonara.com
description: >- # this means to ignore newlines until "baseurl:"
  Reliably reduce the carbon footprint of your business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trycarbonara.github.io" # the base hostname & protocol for your site
swagger: "swagger.html"
google_map_key: ${{ secrets.GOOGLE_MAPS_KEY }}
# twitter_username: jekyllrb
github_username: trycarbonara
show_downloads: false
github:
  is_project_page: true
  readme_url: "https://trycarbonara.github.io/docs/dist/html/getting-started.html"
# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one 
