openapi: 3.0.1
info:
  title: Trycarbonara.NodeApi
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - url: https://08nec61uab.execute-api.us-west-1.amazonaws.com
    description: Trycarbonara API Web Server
paths:
  /staging/generatetoken:
    post:
      tags:
        - Trycarbonara
      summary: Auth Token Generation.
      description: |
        Generates Auth Token to be used with other Trycarbonara APIs.
      operationId: getAuthToken
      requestBody:
        description: Auth Token Generation based on User passed info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarbonaraUserInfoDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/TokenDataDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
  /staging/nodeCarbonaraIdentifyAPI:
    post:
      tags:
        - Trycarbonara
      summary: Calculate the energy consumption & carbon emission data by application usage for location for a specified time stamp
      operationId: getIdentifyResult
      requestBody:
        description: Array of `infrastructureAgentData` data for a `infrastructureComponent` where each contains `cpuUtilization`, `memoryUsed`, `storageUsed`, `networkIn` and `networkOut` for a passed `timeStamp` which to calculate energy consumption (kWh)) and carbon score (tonnes) from average marginal carbon intensity for specified grid info. Note - Recommended to pass only single `infrastructureAgentData` timestamp metrics.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarbonInfrastructureComponentInputDTO'
      parameters:
        - name: authorizationToken
          in: header
          description: Auth Token generated by getAuthToken.
          required: true
          schema:
            type: string
            example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlN
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/CarbonInfrastructureComponentOutputDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal server error
components:
  schemas:
    CarbonaraUserInfoDTO:
      type: object
      properties:
        username:
          type: string
          example: hello
        useremail:
          type: string
          example: abc@xyz.com
    CarbonInfrastructureComponentInputDTO:
      type: object
      properties:
        infrastructureComponent:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureAgentDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
    CarbonInfrastructureComponentOutputDTO:
      type: object
      properties:
        infrastructureComponent:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureAgentOutputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureAgentDTO:
      type: object
      properties:
        infrastructureAgentData:
          type: object
          $ref: '#/components/schemas/CarbonInfrastructureAgentInputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureAgentInputDTO:
      type: object
      properties:
        instanceProvider:
          type: string
          nullable: false
          example: equinix
          description: Supported Types - Partner On-Prem, Data Centers or Networks
        lat:
          type: float
          nullable: false
          example: 47.6062
          description: Node Geo Location - latitude
        lon:
          type: float
          nullable: false
          example: -122.3321
          description: Node Geo Location - longitude
        timezone:
          type: string
          nullable: false
          example: America/Los_Angeles
          description: Timezone for the target node
        instanceType:
          type: string
          nullable: false
          example: c3-small-x86-01
          description: Provider supported Node-Types as defined internally, if applicable. Usually host-name info
        infrastructureType:
          type: string
          nullable: false
          example: baremetal
          description: Target Infrastucture Type
        vCPU:
          type: number
          description: vCPU available
          format: float
          nullable: false
          example: 48
        cpuInfo:
          type: string
          nullable: false
          example: GenuineIntel:158
          description: CPU Vendor/Manufacturer and Model info
        architecture:
          type: string
          nullable: false
          example: Intel(R) Xeon(R) E-2278G CPU @ 3.40GHz
          description: Supported Processor Type
        nodeIP:
          type: string
          nullable: false
          example: 147.28.159.39
          description: Node IP Address
        inputFrequency:
          type: number
          description: frequency of input to be published in second(s)
          format: float
          nullable: false
          example: 3600
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureInputsInputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureAgentOutputDTO:
      type: object
      properties:
        instanceProvider:
          type: string
          nullable: false
          example: equinix
          description: Supported Types - Partner On-Prem, Data Centers or Networks
        latitude:
          type: float
          nullable: false
          example: 47.6062
          description: Node Geo Location - latitude
        longitude:
          type: float
          nullable: false
          example: -122.3321
          description: Node Geo Location - longitude
        instanceType:
          type: string
          nullable: false
          example: c3-small-x86-01
          description: Provider supported Node-Types as defined internally, if applicable. Usually host-name info
        infrastructureType:
          type: string
          nullable: false
          example: baremetal
          description: Target Infrastucture Type
        architecture:
          type: string
          nullable: false
          example: Intel(R) Xeon(R) E-2278G CPU @ 3.40GHz
          description: Supported Processor Type
        instance:
          type: string
          nullable: false
          example: 147.28.159.39
          description: Node IP Address
        inputFrequency:
          type: number
          description: frequency of input to be published in second(s)
          format: float
          nullable: false
          example: 3600
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureInputsOutputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureInputsInputDTO:
      type: object
      properties:
        timeStamp:
          type: string
          format: date-time
          example: 2022-03-10 18:00:00-08:00
          description: Timestamp in ISO Format + Offset
        kwHComputeMemory:
          type: number
          description: Node energy consumption in kWh (check methodology for tooling support)
          format: double
          example: 0.06368856935254683
        ssdStorageAllocated:
          type: number
          description: SSD Disk Utilization in bytes
          format: double
          example: 254198194176
        hddStorageAllocated:
          type: number
          description: HDD Disk Utilization in bytes
          format: double
          example: 100000000
        networkIn:
          type: number
          description: Network In in bytes
          format: double
          example: 3460135.555555556
        networkOut:
          type: number
          description: Network Out in bytes
          format: double
          example: 3742255.555555556
      additionalProperties: false
    CarbonInfrastructureInputsOutputDTO:
      type: object
      properties:
        Timestamp:
          type: string
          format: date-time
          example: 2022-03-10 18:00:00-08:00
          description: Timestamp in ISO Format + Offset
        SSD Storage [bytes]:
          type: number
          description: SSD Disk Utilization in bytes
          format: double
          example: 254198194176.0
        HDD Storage [bytes]:
          type: number
          description: HDD Disk Utilization in bytes
          format: double
          example: 100000000.0
        NetworkIn [bytes]:
          type: number
          description: Network In in bytes, as reported
          format: double
          example: 3460135.555555556
        NetworkOut [bytes]:
          type: number
          description: Network Out in bytes, as reported
          format: double
          example: 3742255.555555556
        MOER [lbs/MWh]:
          type: number
          description: Grid Marginal Carbon Intensity in lbs/MWh
          format: double
          example: 822
        Average Carbon Intensity [lbs/MWh]:
          type: number
          description: Grid Avergage Carbon Intensity in lbs/MWh
          format: double
          example: 52.910942924370616
        carbonfromComputeMemoryMarginal:
          type: number
          description: Marginal Carbon Emission from Compute/Memory in tonnes CO2 eq
          format: double
          example: 3.751946654403649e-05
        carbonfromComputeMemoryAverage:
          type: number
          description: Average Carbon Emission from Compute/Memory in tonnes CO2 eq
          format: double
          example: 2.415073421976092e-06
        carbonfromNetworkInMarginal:
          type: number
          description: Carbon Emission from Network In in tonnes CO2 eq
          format: double
          example: 5.6037354969110334e-08
        carbonfromNetworkInAverage:
          type: number
          description: Carbon Emission from Network In in tonnes CO2 eq
          format: double
          example: 5.6037354969110334e-08
        carbonfromNetworkOutMarginal:
          type: number
          description: Carbon Emission from Network Out in tonnes CO2 eq
          format: double
          example: 5.613046981883499e-08
        carbonfromNetworkOutAverage:
          type: number
          description: Carbon Emission from Network Out in tonnes CO2 eq
          format: double
          example: 5.613046981883499e-08
        carbonfromSsdStorageMarginal:
          type: number
          description: Carbon Emission from Memory in tonnes CO2 eq
          format: double
          example: 1.7970032749481822e-07
        carbonfromSsdStorageAverage:
          type: number
          description: Carbon Emission from Memory in tonnes CO2 eq
          format: double
          example: 1.1567048383903935e-08
        carbonfromHddStorageMarginal:
          type: number
          description: Carbon Emission from Storage in tonnes CO2 eq
          format: double
          example: 3.829204125881104e-11
        carbonfromHddStorageAverage:
          type: number
          description: Carbon Emission from Storage in tonnes CO2 eq
          format: double
          example: 2.464802931268365e-12
        carbonfromEmbodied:
          type: number
          description: Total Carbon Embodied Emission based on the instance type, for CPU type, in tonnes CO2 eq
          format: double
          example: 2.8745719175999996e-05
        carbonTotalMarginal:
          type: number
          description: Total Carbon Emission in tonnes CO2 eq
          format: double
          example: 6.644916732815085e-05
        carbonTotalAverage:
          type: number
          description: Total Carbon Emission in tonnes CO2 eq
          format: double
          example: 3.117263522615866e-05
        KwHComputeMemory:
          type: number
          description: Energy Consumption from Compute/Memory in kWh
          format: double
          example: 0.06368856935254683
        KwHNetworkIn:
          type: number
          description: Energy Consumption from Network In in kWh
          format: double
          example: 3.4601355555555562e-06
        KwHNetworkOut:
          type: number
          description: Energy Consumption from Network Out in kWh
          format: double
          example: 3.742255555555556e-06
        KwHHddStorage:
          type: number
          description: Energy Consumption from HDD Storage in kWh
          format: double
          example: 6.5e-08
        KwHSsdStorage:
          type: number
          description: Energy Consumption from SSD Storage in kWh
          format: double
          example: 0.0003050378330112
      additionalProperties: false
    TokenDataDTO:
      type: object
      properties:
        token:
          type: string
          nullable: false
          example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlN"
      additionalProperties: false
externalDocs:
  description: "Find out more about Tryarbonara"
  url: "https://trycarbonara.github.io"