openapi: 3.0.1
info:
  title: Carbonara.CloudApi
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - url: https://08nec61uab.execute-api.us-west-1.amazonaws.com
    description: Carbonara API Web Server
paths:
  /staging/generatetoken:
    post:
      tags:
        - Carbonara
      summary: Auth Token Generation.
      description: |
        Generates Auth Token to be used with other Carbonara APIs.
      operationId: getAuthToken
      requestBody:
        description: Auth Token Generation based on User passed info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarbonaraUserInfoDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/TokenDataDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
  /staging/cloudIdentify:
    post:
      tags:
        - Carbonara
      summary: Calculate the energy consumption & carbon emission data by application usage for location for a specified time stamp
      operationId: getIdentifyResult
      requestBody:
        description: Array of `infrastructureAgentData` data for a `infrastructureComponent` where each contains `cpuUtilization`, `memoryUsed`, `storageUsed`, `networkIn` and `networkOut` for a passed `timeStamp` which to calculate energy consumption (kWh)) and carbon score (tonnes) from average marginal carbon intensity for specified grid info. Note - Recommended to pass only single `infrastructureAgentData` timestamp metrics.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarbonInfrastructureComponentInputDTO'
      parameters:
        - name: authorizationToken
          in: header
          description: Auth Token generated by getAuthToken.
          required: true
          schema:
            type: string
            example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlN
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/CarbonInfrastructureComponentOutputDTO'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal server error
components:
  schemas:
    CarbonaraUserInfoDTO:
      type: object
      properties:
        username:
          type: string
          example: hello
        useremail:
          type: string
          example: abc@xyz.com
    CarbonInfrastructureComponentInputDTO:
      type: object
      properties:
        infrastructureComponent:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureAgentDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
    CarbonInfrastructureComponentOutputDTO:
      type: object
      properties:
        infrastructureComponent:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureAgentOutputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureAgentDTO:
      type: object
      properties:
        infrastructureAgentData:
          type: object
          $ref: '#/components/schemas/CarbonInfrastructureAgentInputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureAgentInputDTO:
      type: object
      properties:
        cloudProvider:
          type: string
          nullable: false
          example: aws
          description: Supported Types - aws, azure, gcp
        region:
          type: string
          nullable: false
          example: us-east-2
          description: Respective Cloud Provider supported Regions
        instanceType:
          type: string
          nullable: false
          example: t2.xlarge
          description: Respective Cloud Provider supported Node-Types
        infrastructureType:
          type: string
          nullable: false
          example: DaemonSet
          description: Target Worker Type like, Daemon-Set, Container, etc.
        vCPUAllocated:
          type: number
          description: vCPU allocated/requested
          format: float
          nullable: false
          example: 0.1
        jobId:
          type: string
          nullable: false
          description: Container/Job Name
          example: kube-proxy
        runId:
          type: string
          nullable: false
          example: kube-proxy[docker://0dfb498a88354862d5776359ab1f5f198b4f459fe308fcb37afe94c9e4748ae1]
          description: Container/Job Id
        workerId:
          type: string
          nullable: false
          example: kube-proxy-pswwz
          description: Pod/Worker Name
        inputFrequency:
          type: number
          description: frequency of input to be published in second(s)
          format: float
          nullable: false
          example: 300
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureInputsInputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureAgentOutputDTO:
      type: object
      properties:
        cloudProvider:
          type: string
          nullable: false
          example: AWS
          description: Supported Types - aws, azure, gcp
        region:
          type: string
          nullable: false
          example: us-east-2
          description: Respective Cloud Provider supported Regions
        instanceType:
          type: string
          nullable: false
          example: t2.xlarge
          description: Respective Cloud Provider supported Node-Types
        infrastructureType:
          type: string
          nullable: false
          example: DaemonSet
          description: Target Worker Type like, Daemon-Set, Container, etc.
        jobId:
          type: string
          nullable: false
          description: Container/Job Name
          example: kube-proxy
        runId:
          type: string
          nullable: false
          example: kube-proxy[docker://0dfb498a88354862d5776359ab1f5f198b4f459fe308fcb37afe94c9e4748ae1]
          description: Container/Job Id
        workerId:
          type: string
          nullable: false
          example: kube-proxy-pswwz
          description: Pod/Worker Name
        inputFrequency:
          type: number
          description: frequency of input to be published in second(s)
          format: float
          nullable: false
          example: 300
        tariffType:
          type: string
          nullable: false
          example: FIXED_PRICE
          description: State Grid based Tariff (Current Support - FIXED_PRICE)
        tariff:
          type: number
          description: Tariff ($)
          format: float
          nullable: false
          example: 0.075
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/CarbonInfrastructureInputsOutputDTO'
          description: "infrastructureComponent containing infrastructureAgentData array"
          nullable: false
      additionalProperties: false
    CarbonInfrastructureInputsInputDTO:
      type: object
      properties:
        timeStamp:
          type: string
          format: date-time
          example: 2022-03-10 18:00:00-08:00
          description: Timestamp in ISO Format + Offset
        cpuUtilization:
          type: number
          description: CPU Utilization in %
          format: double
          example: 30
        memoryUsed:
          type: number
          description: Memory Utilization in bytes
          format: double
          example: 5000000000
        storageUsed:
          type: number
          description: Disk Utilization in bytes
          format: double
          example: 100000000
        networkIn:
          type: number
          description: Network In in bytes
          format: double
          example: 123048878
        networkOut:
          type: number
          description: Network Out in bytes
          format: double
          example: 123253343
      additionalProperties: false
    CarbonInfrastructureInputsOutputDTO:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: 2022-03-10 18:00:00-08:00
          description: Timestamp in ISO Format + Offset
        marginalCarbonIntensity:
          type: number
          description: Grid Marginal Carbon Intensity in lbs/MWh
          format: double
          example: 1004
        averageCarbonIntensity:
          type: number
          description: Grid Avergage Carbon Intensity in lbs/MWh
          format: double
          example: 246.91
        carbonfromComputeMarginal:
          type: number
          description: Marginal Carbon Emission from Compute in tonnes CO2 eq
          format: double
          example: 6.352931570973682e-08
        carbonfromComputeAverage:
          type: number
          description: Average Carbon Emission from Compute in tonnes CO2 eq
          format: double
          example: 6.352931570973682e-08
        carbonfromNetworkInMarginal:
          type: number
          description: Carbon Emission from Network In in tonnes CO2 eq
          format: double
          example: 5.6037354969110334e-08
        carbonfromNetworkInAverage:
          type: number
          description: Carbon Emission from Network In in tonnes CO2 eq
          format: double
          example: 5.6037354969110334e-08
        carbonfromNetworkOutMarginal:
          type: number
          description: Carbon Emission from Network Out in tonnes CO2 eq
          format: double
          example: 5.613046981883499e-08
        carbonfromNetworkOutAverage:
          type: number
          description: Carbon Emission from Network Out in tonnes CO2 eq
          format: double
          example: 5.613046981883499e-08
        carbonfromMemoryMarginal:
          type: number
          description: Carbon Emission from Memory in tonnes CO2 eq
          format: double
          example: 7.438318924198577e-08
        carbonfromMemoryAverage:
          type: number
          description: Carbon Emission from Memory in tonnes CO2 eq
          format: double
          example: 7.438318924198577e-08
        carbonfromStorageMarginal:
          type: number
          description: Carbon Emission from Storage in tonnes CO2 eq
          format: double
          example: 2.466789439147487e-12
        carbonfromStorageAverage:
          type: number
          description: Carbon Emission from Storage in tonnes CO2 eq
          format: double
          example: 2.466789439147487e-12
        carbonFromEmbodied:
          type: number
          description: Total Carbon Embodied Emission based on the instance type, for allocated vCPU, in tonnes CO2 eq
          format: double
          example: 0.0010647816666666666
        carbonTotalMarginal:
          type: number
          description: Total Carbon Emission in tonnes CO2 eq
          format: double
          example: 2.500827965291071e-07
        carbonTotalAverage:
          type: number
          description: Total Carbon Emission in tonnes CO2 eq
          format: double
          example: 2.500827965291071e-07
        kwHCompute:
          type: number
          description: Energy Consumption from Compute in kWh
          format: double
          example: 0.00013949999999999998
        kwHNetworkIn:
          type: number
          description: Energy Consumption from Network In in kWh
          format: double
          example: 0.00012304887800000002
        kwHNetworkOut:
          type: number
          description: Energy Consumption from Network Out in kWh
          format: double
          example: 0.000123253343
        kwHMemory:
          type: number
          description: Energy Consumption from Memory in kWh
          format: double
          example: 0.00016333333333333334
        kwHStorage:
          type: number
          description: Energy Consumption from Storage in kWh
          format: double
          example: 5.416666666666666e-09
      additionalProperties: false
    TokenDataDTO:
      type: object
      properties:
        token:
          type: string
          nullable: false
          example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlN"
      additionalProperties: false
externalDocs:
  description: "Find out more about Carbonara"
  url: "https://trycarbonara.github.io"